In [100]:
import sympy as smp
from sympy import *
import numpy as np
from numpy import *
import scipy as sp
from scipy.integrate import solve_ivp
from scipy.interpolate import interp1d
from scipy.integrate import odeint
from fractions import Fraction
import matplotlib.pyplot as plt
import scienceplots
plt.style.use(['science', 'notebook', 'grid'])

x, y, t, n, a, b, C, c, r, u, s, A, d = smp.symbols('x y t n a b C c r u s A d')
f, g, m = smp.symbols('f g m', cls=smp.Function)

In [2]:
# Eivenvalues

A = np.array([[8, -12], [2, -2]])

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

print(eigenvalues)

[4. 2.]


In [3]:
# Eivenvalues

A = np.array([[11, -20], [4, -7]])

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

print(eigenvalues)

[3. 1.]


In [5]:
# Find the spectrum of the matrix

A = np.array([[5, -2], [1, 2]])

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

print(eigenvalues)

[4. 3.]


In [6]:
# Find the spectrum of the matrix

A = np.array([[1, 0], [0, 1]])

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

print(eigenvalues)

[1. 1.]


In [7]:
# Find the spectrum of the matrix

A = np.array([[3, -2], [1, 0]])

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

print(eigenvalues)

[2. 1.]


In [9]:
# Find the spectrum of the matrix

A = np.array([[4, -6], [1, -1]])

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

print(eigenvalues)

[2. 1.]


In [11]:
# PART I

# Define the matrix
A = np.array([[4, 0, 0, 0], [-2, 5, 0, 0], [1, -3, 4, 0], [5, 1, 1, 5]])

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

# Print the eigenvalues
print(eigenvalues)

[5. 4. 5. 4.]


In [12]:
# PART II

from collections import Counter

# Compute the algebraic multiplicities
multiplicities = Counter(eigenvalues)

# Print the algebraic multiplicities
for eigenvalue, multiplicity in multiplicities.items():
    print(f"Eigenvalue: {eigenvalue}, Algebraic multiplicity: {multiplicity}")

Eigenvalue: 5.0, Algebraic multiplicity: 2
Eigenvalue: 4.0, Algebraic multiplicity: 2


In [13]:
# PART I

# Define the matrix
A = np.array([[9, 0, 0, 0], [4, 7, 0, 0], [2, -2, 9, 0], [5, 4, 5, 7]])

# Compute the eigenvalues
eigenvalues = np.linalg.eigvals(A)

# Print the eigenvalues
print(eigenvalues)

[7. 9. 7. 9.]


In [14]:
# PART II

from collections import Counter

# Compute the algebraic multiplicities
multiplicities = Counter(eigenvalues)

# Print the algebraic multiplicities
for eigenvalue, multiplicity in multiplicities.items():
    print(f"Eigenvalue: {eigenvalue}, Algebraic multiplicity: {multiplicity}")

Eigenvalue: 7.0, Algebraic multiplicity: 2
Eigenvalue: 9.0, Algebraic multiplicity: 2


In [17]:
# (lambda)^3 + 2(lambda)^2 - 4(lambda) - 8 = 0

from collections import Counter

# Define the coefficients of the characteristic polynomial
coefficients = [1, 2, -4, -8]

# Compute the roots of the polynomial, which are the eigenvalues of the matrix
eigenvalues = np.roots(coefficients)

# Compute the algebraic multiplicities
multiplicities = Counter(eigenvalues)

# Print the eigenvalues and their algebraic multiplicities
for eigenvalue, multiplicity in multiplicities.items():
    print(f"Eigenvalue: {eigenvalue}, Algebraic multiplicity: {multiplicity}")

Eigenvalue: 1.9999999999999998, Algebraic multiplicity: 1
Eigenvalue: -2.0000000102548543, Algebraic multiplicity: 1
Eigenvalue: -1.9999999897451473, Algebraic multiplicity: 1


In [27]:
from collections import Counter

# Define the coefficients of the characteristic polynomial
coefficients = [1, 2, -4, -8]

# Compute the roots of the polynomial, which are the eigenvalues of the matrix
eigenvalues = np.roots(coefficients)

# Round the eigenvalues to mitigate precision issues
eigenvalues = [round(ev, 5) for ev in eigenvalues]

# Compute the algebraic multiplicities
multiplicities = Counter(eigenvalues)

# Print the eigenvalues and their algebraic multiplicities
for eigenvalue, multiplicity in multiplicities.items():
    print(f"Eigenvalue: {eigenvalue}, Algebraic multiplicity: {multiplicity}")

Eigenvalue: 2.0, Algebraic multiplicity: 1
Eigenvalue: -2.0, Algebraic multiplicity: 2


In [28]:
from collections import Counter

# Define the coefficients of the characteristic polynomial
coefficients = [1, -4, -16, 64]

# Compute the roots of the polynomial, which are the eigenvalues of the matrix
eigenvalues = np.roots(coefficients)

# Round the eigenvalues to mitigate precision issues
eigenvalues = [round(ev, 5) for ev in eigenvalues]

# Compute the algebraic multiplicities
multiplicities = Counter(eigenvalues)

# Print the eigenvalues and their algebraic multiplicities
for eigenvalue, multiplicity in multiplicities.items():
    print(f"Eigenvalue: {eigenvalue}, Algebraic multiplicity: {multiplicity}")

Eigenvalue: -4.0, Algebraic multiplicity: 1
Eigenvalue: 4.0, Algebraic multiplicity: 2


In [30]:
# Geometric Multiplicities

# Define the eigenbases for each eigenvalue
eigenbasis_5 = [[5, 2, 7, 3]]
eigenbasis_1 = [[-9, -4, 12, -8], [6, -2, 1, -5], [-6, -11, -7, 4]]

# Compute the geometric multiplicities
geometric_multiplicity_5 = len(eigenbasis_5)
geometric_multiplicity_1 = len(eigenbasis_1)

# Print the geometric multiplicities
print(f"Geometric multiplicity of lambda = 5: {geometric_multiplicity_5}")
print(f"Geometric multiplicity of lambda = 1: {geometric_multiplicity_1}")

Geometric multiplicity of lambda = 5: 1
Geometric multiplicity of lambda = 1: 3


In [31]:
# Define the matrices P, D, and P^-1
P = np.array([[5, 2], [2, 1]])
D = np.array([[4, 0], [0, 1]])
P_inv = np.array([[1, -2], [-2, 5]])

# Compute the product PDP^-1
A = P @ D @ P_inv

# Print the result
print(A)

[[ 16 -30]
 [  6 -11]]


# Euclidean Inner Product = np.dot

In [32]:
A = np.array([4, 2, -4])
B = np.array([1, 0, 3])
np.dot(A, B)

-8

In [33]:
A = np.array([-4, -1])
B = np.array([1, 3])
np.dot(A, B)

-7

In [36]:
# -3(v1)(u1) - 2(v2)(u2)

# Define the vectors
u = np.array([-4, -1])
v = np.array([1, 3])

# Define the weights
weights = np.array([-3, -2])

# Calculate the weighted inner product
inner_product = np.sum(weights * u * v)

print(inner_product)

18


In [37]:
# 2(v1)(u1) - 4(v2)(u2)

# Define the vectors
u = np.array([-4, -3])
v = np.array([-2, 1])

# Define the weights
weights = np.array([2, -4])

# Calculate the weighted inner product
inner_product = np.sum(weights * u * v)

print(inner_product)

28


# Frobenius Product = np.sum

In [38]:
# Define the matrices
A = np.array([[0, 2, -8], [-9, -2, -6]])
B = np.array([[-9, -3, -2], [-6, -8, 0]])

# Calculate the Frobenius inner product
inner_product = np.sum(A * B)

print(inner_product)

80


In [39]:
import scipy.integrate as spi

# Define the functions
def f(x):
    return 16*x

def g(x):
    return 3*x**2

# Define the inner product function
def inner_product(x):
    return f(x) * g(x)

# Calculate the inner product
inner_product_value, error = spi.quad(inner_product, -2, 3)

print(inner_product_value)

780.0


# Euclidean Distance = np.norm

In [41]:
# Define the vectors
m = np.array([-3, 4])
n = np.array([-10, -20])

# Compute the Euclidean distance
distance = np.linalg.norm(m - n)

print(distance)

25.0


In [45]:
# Frobenius Distance

# Define the matrices
A = np.array([[-2/np.sqrt(18), -4/np.sqrt(18)], [4/np.sqrt(18), 3/np.sqrt(18)]])
B = np.array([[-8/np.sqrt(18), -7/np.sqrt(18)], [13/np.sqrt(18), 9/np.sqrt(18)]])

# Compute the Frobenius distance
distance = np.linalg.norm(A - B)

print(distance)

3.0000000000000004


In [46]:
# Frobenius Distance

# Define the matrices
A = np.array([[-2/np.sqrt(18), 2/np.sqrt(18)], [-1/np.sqrt(18), 3/np.sqrt(18)]])
B = np.array([[-10/np.sqrt(18), 14/np.sqrt(18)], [7/np.sqrt(18), -1/np.sqrt(18)]])

# Compute the Frobenius distance
distance = np.linalg.norm(A - B)

print(distance)

4.0


In [47]:
# Weighted Euclidean Distance
# u, v and weights w

# Define the vectors and weights
u = np.array([-4, 2])
v = np.array([-9, -9])
w = np.array([3, 1])

# Compute the weighted Euclidean distance
distance = np.sqrt(np.sum(w * (u - v)**2))

print(distance)

14.0


In [50]:
from scipy.integrate import quad

# Define the functions
def f(x):
    return 12*x - 1

def g(x):
    return 3*x + 5

# Define the integrand
def integrand(x):
    return (f(x) - g(x))**2

# Compute the integration distance
result, error = quad(integrand, 0, 1)
distance = np.sqrt(result)

print(distance)

3.0


In [52]:
# Weighted Integration Distance

from scipy.integrate import quad

# Define the functions
def f(x):
    return 5*x+1

def g(x):
    return 2*x-3

# Define the integrand
def integrand(x):
    return (f(x) - g(x))**2

# Compute the integration distance
result, error = quad(integrand, 0, 1)
distance = np.sqrt(result)

print(distance)

5.5677643628300215


In [54]:
# Weighted Integration Distance

from scipy.integrate import quad

# Define the functions
def f(x):
    return 3*x+1

def g(x):
    return 2*x+4

# Define the weight function
def w(x):
    # replace this with your weight function
    return 8*x

# Define the integrand
def integrand(x):
    return w(x) * (f(x) - g(x))**2

# Compute the weighted integration distance
result, error = quad(integrand, 0, 1)
distance = np.sqrt(result)

print(distance)

4.69041575982343


In [55]:
# Weighted Integration Distance

from scipy.integrate import quad

# Define the functions
def f(x):
    return 3*x-1

def g(x):
    return 2*x+2

# Define the weight function
def w(x):
    # replace this with your weight function
    return 12*x

# Define the integrand
def integrand(x):
    return w(x) * (f(x) - g(x))**2

# Compute the weighted integration distance
result, error = quad(integrand, 0, 1)
distance = np.sqrt(result)

print(distance)

5.744562646538029


In [56]:
# Define the vectors
m = np.array([3, 4])

# Compute the Euclidean distance
distance = np.linalg.norm(m)

print(distance)

5.0


In [59]:
# Frobenius Norm

# Define the matrix
A = np.array([[8/np.sqrt(10), -8/np.sqrt(10)], [4/np.sqrt(10), -4/np.sqrt(10)]])

# Compute the Frobenius norm
norm = np.linalg.norm(A)

print(norm)

4.0


In [60]:
# Frobenius Norm

# Define the matrix
A = np.array([[2/np.sqrt(18), -2/np.sqrt(18)], [3/np.sqrt(18), 1/np.sqrt(18)]])

# Compute the Frobenius norm
norm = np.linalg.norm(A)

print(norm)

1.0


In [61]:
# Weighted Euclidean Distance
# v and weights w

# Define the vectors and weights
v = np.array([7, 6])
w = np.array([1, 2])

# Compute the weighted Euclidean distance
distance = np.sqrt(np.sum(w * (v)**2))

print(distance)

11.0


In [63]:
# Integration Norm of the given polynomial on C[0, 1]
# f(x) = 9x+6

from scipy.integrate import quad

# Define the function
def f(x):
    return 9*x + 6

# Perform the integration
result, error = quad(f, 0, 1)

print("The integration norm is:", result)

The integration norm is: 10.5


In [64]:
# Weighted Integration norm <f, f> = ∫(0, 1)f(x)f(x)w(x)dx of the given polynomial on C[0,1]
# f(x) = x+3 with w(x) = 4x



1.7320508075688774


In [66]:
# Weighted Integration Norm

from scipy.integrate import quad

# Define the functions
def f(x):
    return x-3

# Define the weight function
def w(x):
    # replace this with your weight function
    return 12*x

# Define the integrand
def integrand(x):
    return w(x) * (f(x))**2

# Compute the weighted integration distance
result, error = quad(integrand, 0, 1)
distance = np.sqrt(result)

print(distance)

5.744562646538029


# Orthogonal Basis

In [68]:
# Define the original vectors
u1 = np.array([-3, 0])
u2 = np.array([-4, 2])

# Initialize the orthogonal vectors
v1 = u1
v2 = u2

# Apply the Gram-Schmidt process
v2 = u2 - (np.dot(u2, v1) / np.dot(v1, v1)) * v1

# Print the orthogonal vectors
print("v1:", v1)
print("v2:", v2)

v1: [-3  0]
v2: [0. 2.]


In [69]:
# Define the original vectors
u1 = np.array([2, 4, 0])
u2 = np.array([-40, 20, 20])
u3 = np.array([3, -3, 1])

# Initialize the orthogonal vectors
v1 = u1
v2 = u2
v3 = u3

# Apply the Gram-Schmidt process
v2 = u2 - (np.dot(u2, v1) / np.dot(v1, v1)) * v1
v3 = u3 - (np.dot(u3, v1) / np.dot(v1, v1)) * v1 - (np.dot(u3, v2) / np.dot(v2, v2)) * v2

# Print the orthogonal vectors
print("v1:", v1)
print("v2:", v2)
print("v3:", v3)

v1: [2 4 0]
v2: [-40.  20.  20.]
v3: [ 0.93333333 -0.46666667  2.33333333]


In [70]:
# Define the original vectors
u1 = np.array([-1, 0, 0])
u2 = np.array([1, -3, 0])
u3 = np.array([2, 3, -4])

# Initialize the orthogonal vectors
v1 = u1
v2 = u2
v3 = u3

# Apply the Gram-Schmidt process
v2 = u2 - (np.dot(u2, v1) / np.dot(v1, v1)) * v1
v3 = u3 - (np.dot(u3, v1) / np.dot(v1, v1)) * v1 - (np.dot(u3, v2) / np.dot(v2, v2)) * v2

# Print the orthogonal vectors
print("v1:", v1)
print("v2:", v2)
print("v3:", v3)

v1: [-1  0  0]
v2: [ 0. -3.  0.]
v3: [ 0.  0. -4.]


In [71]:
# Define the original vectors
u1 = np.array([2, 0, 0])
u2 = np.array([-1, 1, 0])
u3 = np.array([-3, 3, -2])

# Initialize the orthogonal vectors
v1 = u1
v2 = u2
v3 = u3

# Apply the Gram-Schmidt process
v2 = u2 - (np.dot(u2, v1) / np.dot(v1, v1)) * v1
v3 = u3 - (np.dot(u3, v1) / np.dot(v1, v1)) * v1 - (np.dot(u3, v2) / np.dot(v2, v2)) * v2

# Print the orthogonal vectors
print("v1:", v1)
print("v2:", v2)
print("v3:", v3)

v1: [2 0 0]
v2: [0. 1. 0.]
v3: [ 0.  0. -2.]


In [73]:
# Define the original matrices
U1 = np.array([[-1, 0], [-2, 2]])
U2 = np.array([[0, -18], [18, 0]])
U3 = np.array([[-2, -1], [0, 2]])

# Initialize the orthogonal matrices
V1 = U1
V2 = U2
V3 = U3

# Define the Frobenius inner product
def frobenius_inner_product(A, B):
    return np.sum(A * B)

# Apply the Gram-Schmidt process
V2 = U2 - (frobenius_inner_product(U2, V1) / frobenius_inner_product(V1, V1)) * V1
V3 = U3 - (frobenius_inner_product(U3, V1) / frobenius_inner_product(V1, V1)) * V1 - (frobenius_inner_product(U3, V2) / frobenius_inner_product(V2, V2)) * V2

# Print the orthogonal matrices
print("V1:\n", V1)
print("V2:\n", V2)
print("V3:\n", V3)

V1:
 [[-1  0]
 [-2  2]]
V2:
 [[ -4. -18.]
 [ 10.   8.]]
V3:
 [[-1.00000000e+00  5.00000000e-01]
 [ 5.00000000e-01  1.11022302e-16]]


In [74]:
# Define the original matrices
U1 = np.array([[1, 0], [-2, -1]])
U2 = np.array([[0, 6], [6, 0]])
U3 = np.array([[1, -3], [0, 1]])

# Initialize the orthogonal matrices
V1 = U1
V2 = U2
V3 = U3

# Define the Frobenius inner product
def frobenius_inner_product(A, B):
    return np.sum(A * B)

# Apply the Gram-Schmidt process
V2 = U2 - (frobenius_inner_product(U2, V1) / frobenius_inner_product(V1, V1)) * V1
V3 = U3 - (frobenius_inner_product(U3, V1) / frobenius_inner_product(V1, V1)) * V1 - (frobenius_inner_product(U3, V2) / frobenius_inner_product(V2, V2)) * V2

# Print the orthogonal matrices
print("V1:\n", V1)
print("V2:\n", V2)
print("V3:\n", V3)

V1:
 [[ 1  0]
 [-2 -1]]
V2:
 [[ 2.  6.]
 [ 2. -2.]]
V3:
 [[ 1.75 -0.75]
 [ 0.75  0.25]]


# Orthogonal Projection

In [76]:
# Define the vectors
y = np.array([5, 1, -7, 3])
u = np.array([1, 0, -1, 2])

# Calculate the dot products
dot_product_yu = np.dot(y, u)
dot_product_uu = np.dot(u, u)

# Calculate the scalar multiple
scalar = dot_product_yu / dot_product_uu

# Calculate the orthogonal projection
projection = scalar * u

print(projection)

[ 3.  0. -3.  6.]


In [78]:
# Define the vectors
y = np.array([-4, 1, 5])
u1 = np.array([2, 0, -3])
u2 = np.array([3, 0, 2])

# Calculate the dot products
dot_product_yu1 = np.dot(y, u1)
dot_product_u1u1 = np.dot(u1, u1)
dot_product_yu2 = np.dot(y, u2)
dot_product_u2u2 = np.dot(u2, u2)

# Calculate the scalar multiples
scalar1 = dot_product_yu1 / dot_product_u1u1
scalar2 = dot_product_yu2 / dot_product_u2u2

# Calculate the orthogonal projections
projection1 = scalar1 * u1
projection2 = scalar2 * u2

# The orthogonal projection of y onto W is the sum of the projections onto u1 and u2
projection = projection1 + projection2

print(projection)

[-4. -0.  5.]


In [79]:
# Define the vectors
y = np.array([2, 5, 1])
y_parallel_W = np.array([1, 4, 0])  # replace with the actual values of y_parallel_W

# Calculate y_perp_W
y_perp_W = y - y_parallel_W

print(y_perp_W)

[1 1 1]


In [83]:
# For A, find the orthogonal vectors v1, v2, v3 to be used in constructing the orthogonal matrix Q

# Define the column vectors of A
a1 = np.array([3, 0, 0])
a2 = np.array([-1, 2, 0])
a3 = np.array([-3, -4, 1])

# Apply the Gram-Schmidt process
v1 = a1
v2 = a2 - np.dot(a2, v1) / np.dot(v1, v1) * v1
v3 = a3 - np.dot(a3, v1) / np.dot(v1, v1) * v1 - np.dot(a3, v2) / np.dot(v2, v2) * v2

print("v1:", v1)
print("v2:", v2)
print("v3:", v3)

v1: [3 0 0]
v2: [0. 2. 0.]
v3: [0. 0. 1.]


In [89]:
# Find Q for the QR factorization of A given the orthogonal vectors v1, v2, v3

# Define the vectors
v1 = np.array([1, 0, -2])
v2 = np.array([4, -10, 2])
v3 = np.array([-1.67, -0.83, -0.83])

# Calculate the norms of the vectors
norm_v1 = np.linalg.norm(v1)
norm_v2 = np.linalg.norm(v2)
norm_v3 = np.linalg.norm(v3)

# Normalize the vectors
v1_normalized = v1 / norm_v1
v2_normalized = v2 / norm_v2
v3_normalized = v3 / norm_v3

# Form the Q matrix
Q = np.column_stack((v1_normalized, v2_normalized, v3_normalized))

print(Q)

[[ 0.4472136   0.36514837 -0.8181263 ]
 [ 0.         -0.91287093 -0.40661367]
 [-0.89442719  0.18257419 -0.40661367]]


In [91]:
# Find QR factorization of A given Q

# Define matrix A
A = np.array([
    [0, -1, 0],
    [4, 0, 1],
    [-4, -2, 0]
])

# Define matrix Q
Q = np.array([
    [0, -0.58, -0.82],
    [0.71, -0.58, 0.41],
    [-0.71, -0.58, 0.41]
])

# Compute R
R = np.dot(Q.T, A)

print("Matrix R:")
print(R)

Matrix R:
[[ 5.68  1.42  0.71]
 [ 0.    1.74 -0.58]
 [ 0.    0.    0.41]]


In [94]:
# Find QR factorization of A given Q

# Define matrix A
A = np.array([
    [0, 3, 0],
    [4, 0, -3],
    [-4, -1, 0]
])

# Define matrix Q
Q = np.array([
    [0, 0.97, -0.23],
    [0.71, -0.16, -0.69],
    [-0.71, -0.16, -0.69]
])

# Compute R
R = np.dot(Q.T, A)

print("Matrix R:")
print(R)

Matrix R:
[[ 5.68000000e+00  7.10000000e-01 -2.13000000e+00]
 [ 0.00000000e+00  3.07000000e+00  4.80000000e-01]
 [ 0.00000000e+00 -1.11022302e-16  2.07000000e+00]]


In [95]:
# Find the QR factorization of A

# Define matrix A
A = np.array([
    [1, 3],
    [-1, 0]
])

# Calculate the first column of Q (q1) as the normalization of the first column of A
q1 = A[:, 0] / np.linalg.norm(A[:, 0])

# Calculate the second column of Q (q2) as the orthogonalization of the second column of A with respect to q1, and then normalize it
q2 = (A[:, 1] - np.dot(q1, A[:, 1]) * q1) / np.linalg.norm(A[:, 1] - np.dot(q1, A[:, 1]) * q1)

# Form the Q matrix
Q = np.column_stack((q1, q2))

# Compute R
R = np.dot(Q.T, A)

print("Matrix Q:")
print(Q)
print("\nMatrix R:")
print(R)

Matrix Q:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Matrix R:
[[1.41421356e+00 2.12132034e+00]
 [2.22044605e-16 2.12132034e+00]]


In [96]:
# In a singular value decomposition of matrix A where the eigenvalues of (A^T)A are (lambda)1 and (lambda)2, what is Sigma?

# Define the eigenvalues
eigenvalues = np.array([6, 1])

# Calculate the singular values as the square roots of the eigenvalues
singular_values = np.sqrt(eigenvalues)

# Create the Sigma matrix
Sigma = np.zeros((4, 2))
Sigma[0, 0] = singular_values[0]
Sigma[1, 1] = singular_values[1]

print("Sigma matrix:")
print(Sigma)

Sigma matrix:
[[2.44948974 0.        ]
 [0.         1.        ]
 [0.         0.        ]
 [0.         0.        ]]


In [98]:
from sympy import Matrix, sqrt

# Define the matrix A
A = Matrix([
    [1, 0],
    [0, 1],
    [0, 0],
    [-2, 1]
])

# Compute A^T * A
AtA = A.transpose() * A

# Compute the eigenvectors of A^T * A
eigenvectors = AtA.eigenvects()

# Extract the eigenvectors corresponding to the eigenvalues 6 and 1
# Note: The eigenvects() function returns a list of tuples, where each tuple is of the form (eigenvalue, multiplicity, [eigenvector])
v1 = eigenvectors[0][2][0] if eigenvectors[0][0] == 6 else eigenvectors[1][2][0]
v2 = eigenvectors[0][2][0] if eigenvectors[0][0] == 1 else eigenvectors[1][2][0]

# Normalize the eigenvectors
v1_normalized = v1 / v1.norm()
v2_normalized = v2 / v2.norm()

# Form the V matrix
V = Matrix.hstack(v1_normalized, v2_normalized)

print("Matrix V:")
V

Matrix V:


Matrix([
[-2*sqrt(5)/5,   sqrt(5)/5],
[   sqrt(5)/5, 2*sqrt(5)/5]])

In [99]:
# In a singular value decomposition of matrix A with Sigma and V, what is U?

# Define the matrix A
A = np.array([
    [8, -4, -4, 0],
    [0, -4, -4, 8]
])

# Define the matrix Sigma
Sigma = np.array([
    [11.31, 0, 0, 0],
    [0, 8, 0, 0]
])

# Define the matrix V
V = np.array([
    [0.5, -0.71, 0.41, 0],
    [-0.5, 0, 0.82, -0.71],
    [-0.5, 0, 0, 0.71],
    [0.5, 0.71, 0.41, 0]
])

# Compute U
U = A @ V[:, :2] @ np.linalg.inv(Sigma[:2, :2])

print("Matrix U:")
print(U)

Matrix U:
[[ 0.70733864 -0.71      ]
 [ 0.70733864  0.71      ]]


# Pseudoinverse

In [101]:
# Define the matrix
A = np.array([[1, 1], [0, 1]])

# Compute the pseudoinverse
A_pinv = np.linalg.pinv(A)

print(A_pinv)

[[ 1.00000000e+00 -1.00000000e+00]
 [-8.51707167e-17  1.00000000e+00]]


In [102]:
# Define the matrix
A = np.array([[2], [1], [1]])

# Compute the pseudoinverse
A_pinv = np.linalg.pinv(A)

print(A_pinv)

[[0.33333333 0.16666667 0.16666667]]


In [103]:
# Define the matrix
A = np.array([[2, 1], [2, 1]])

# Compute the pseudoinverse
A_pinv = np.linalg.pinv(A)

print(A_pinv)

[[0.2 0.2]
 [0.1 0.1]]


# Conjugate Transpose

In [104]:
# Define the matrix
A = np.array([[1-4j, -3-2j], [3-1j, 2+4j]])

# Compute the conjugate transpose
A_star = A.conj().T

print(A_star)

[[ 1.+4.j  3.+1.j]
 [-3.+2.j  2.-4.j]]


In [105]:
# Define the matrix
A = np.array([[-2, 4-3j], [1j, 2-5j]])

# Compute the conjugate transpose
A_star = A.conj().T

print(A_star)

[[-2.-0.j  0.-1.j]
 [ 4.+3.j  2.+5.j]]


In [106]:
# Define the matrix
A = np.array([[-4, -3+1j], [3j, 2-2j]])

# Compute the conjugate transpose
A_star = A.conj().T

print(A_star)

[[-4.-0.j  0.-3.j]
 [-3.-1.j  2.+2.j]]


In [107]:
# Define the matrix
A = np.array([[-7, -2-6j, -5+2j], [1-3j, 4+3j, -1+6j]])

# Compute the conjugate transpose
A_star = A.conj().T

print(A_star)

[[-7.-0.j  1.+3.j]
 [-2.+6.j  4.-3.j]
 [-5.-2.j -1.-6.j]]


In [108]:
# Calculate (A^T)A and (A^T)b given A and b

# Define the matrix A and vector b
A = np.array([[1, 13], [1, 22], [1, 17], [1, 20]])
b = np.array([[242.8], [368.8], [304.4], [347.8]])

# Compute (A^T)A
AtA = np.dot(A.T, A)

# Compute (A^T)b
Atb = np.dot(A.T, b)

print("(A^T)A:")
print(AtA)

print("(A^T)b:")
print(Atb)

(A^T)A:
[[   4   72]
 [  72 1342]]
(A^T)b:
[[ 1263.8]
 [23400.8]]


In [110]:
# Find the least-squares line given the matrix products (A^T)A and (A^T)b

# Define the matrix (A^T)A and vector (A^T)b
AtA = np.array([[4, 42], [42, 586]])
Atb = np.array([1056.6, 13766.4])

# Solve for x
x = np.linalg.solve(AtA, Atb)

print("The coefficients are:", x)

# y = 70.65 + 18.73x

The coefficients are: [70.65310345 18.42827586]


In [115]:
# Find the least-squares line given the matrix products (A^T)A and (A^T)b

# Define the matrix (A^T)A and vector (A^T)b
AtA = np.array([[4, 72], [72, 1304]])
Atb = np.array([1582.8, 28677.4])

# Solve for x
x = np.linalg.solve(AtA, Atb)

print("The coefficients are:", x)

# y = -25.05 + 23.375x

The coefficients are: [-25.05   23.375]
