In [54]:
import sympy as smp
from sympy import *
import numpy as np
from numpy import *
import scipy as sp
from scipy.integrate import solve_ivp
from scipy.interpolate import interp1d
from scipy.integrate import odeint
from fractions import Fraction
import matplotlib.pyplot as plt
import scienceplots
plt.style.use(['science', 'notebook', 'grid'])

x, y, t, n, a, b, C, c, r, u, s, A = smp.symbols('x y t n a b C c r u s A')
f, g, m = smp.symbols('f g m', cls=smp.Function)

In [13]:
# np.array([[x+2], [2]])
# np.array([[y+4], [-1]])

# Define the equations
eq1 = Eq(x + 2, 2)
eq2 = Eq(y + 4, -1)

# Solve the equations
sol = solve((eq1,eq2), (x, y))

sol

{x: 0, y: -5}

In [12]:
# np.array([[x+1], [0]])
# np.array([[-6], [y-3]])

# Define the equations
eq1 = Eq(x + 1, 0)
eq2 = Eq(-6, y-3)

# Solve the equations
sol = solve((eq1,eq2), (x, y))

sol

{x: -1, y: -3}

In [15]:
# np.array([[-4x-1], [2], [4y-5]])
# np.array([[-9], [2], [11]])

eq1 = Eq(-4*x - 1, -9)
eq2 = Eq(2, 2)
eq3 = Eq(4*y - 5, 11)

sol = solve((eq1, eq3), (x, y))

sol

{x: 2, y: 4}

In [17]:
# np.array([[x+y], [2x+y]])
# np.array([[3], [1]])

A = np.array([[1, 1], [2, 1]])
B = np.array([3, 1])

X = np.linalg.solve(A, B)

X

array([-2.,  5.])

In [19]:
v1 = np.array([[8], [-8]])
v2 = np.array([[4], [-3]])
a1 = -2
a2 = 3

A = np.multiply(a1, v1)
B = np.multiply(a2, v2)

A + B

array([[-4],
       [ 7]])

In [20]:
v1 = np.array([[-4], [-6], [-8]])
v2 = np.array([[-2], [5], [4]])
v3 = np.array([[-8], [8], [-7]])
a1 = 2
a2 = 5
a3 = 4

A = np.multiply(a1, v1)
B = np.multiply(a2, v2)
C = np.multiply(a3, v3)

A + B + C

array([[-50],
       [ 45],
       [-24]])

In [25]:
# Find the weights that should be used for b = (a1)(v1) + (a2)(v2) to obtain b

v1 = np.array([2, -1])
v2 = np.array([2, 2])
b = np.array([12, 6])

# Combine v1 and v2 into a matrix A
A = np.vstack((v1, v2)).T

# Solve the system of equations Ax = b for x using least squares method
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

x

array([2., 4.])

In [26]:
# Find the weights that should be used for b = (a1)(v1) + (a2)(v2) to obtain b

a1 = np.array([3, 2])
a2 = np.array([-1, 3])
b = np.array([7, 1])

# Combine v1 and v2 into a matrix A
A = np.vstack((a1, a2)).T

# Solve the system of equations Ax = b for x using least squares method
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

x

array([ 2., -1.])

In [27]:
# Find the weights that should be used for b = (a1)(v1) + (a2)(v2) to obtain b

a1 = np.array([7, 3, 5])
a2 = np.array([5, -5, 3])
a3 = np.array([-3, 2, -7])
b = np.array([16, -8, 0])

# Combine v1 and v2 into a matrix A
A = np.vstack((a1, a2, a3)).T

# Solve the system of equations Ax = b for x using least squares method
x, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

x

array([1., 3., 2.])

In [30]:
# Define the matrix
matrixS = Matrix([
    [1, 2, 0, 0],
    [0, 3, 0, 0],
    [2, 0, 1, 0],
    [0, 0, 0, 0]
])

# Convert to reduced row echelon form
reducedS, pivots = matrixS.rref()

reducedS

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 0]])

# How to find R^n

In [35]:
def standard_basis(n):
    # Create an n x n identity matrix. Each row of this matrix is a basis vector.
    basis = np.eye(n)
    return basis

n = 10
basis = standard_basis(n)

# Print the basis
for vector in basis:
    print(vector)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [36]:
def standard_basis(n):
    # Create an n x n identity matrix. Each row of this matrix is a basis vector.
    basis = [[1, 3]]
    return basis

n = 10
basis = standard_basis(n)

# Print the basis
for vector in basis:
    print(vector)

[1, 3]


In [37]:
# Define the matrices
M1 = np.array([[1, 0], [-1, 2]])
M2 = np.array([[0, 0], [0, 0]])

# Stack the matrices horizontally
A = np.hstack((M1.reshape(4,1), M2.reshape(4,1)))

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(A)

# The rank of the matrix is equal to the number of linearly independent vectors
print("The rank of the matrix is:")
display(rank)

The rank of the matrix is:


1

In [38]:
# Define the matrices
M1 = np.array([[1, 0], [-1, 2]])
M2 = np.array([[0, 0], [0, 0]])

# Stack the matrices horizontally
A = np.hstack((M1.reshape(4,1), M2.reshape(4,1)))

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(A)

# The rank of the matrix is equal to the number of linearly independent vectors
print("The rank of the matrix is:")
display(rank)

The rank of the matrix is:


1

In [43]:
# Finding a basis for the subspace

from sympy import symbols, Eq, solve, Matrix

# Define the matrix W
W = Matrix([[8*a + 2*b, 3*b], [4*a, 9*b]])

# Express W as a linear combination of M1 and M2
M1 = Matrix([[W[0,0].coeff(a), 0], [W[1,0].coeff(a), 0]])
M2 = Matrix([[W[0,0].coeff(b), W[0,1].coeff(b)], [0, W[1,1].coeff(b)]])

print("M1:")
display(M1)

print("M2:")
display(M2)

M1:


Matrix([
[8, 0],
[4, 0]])

M2:


Matrix([
[2, 3],
[0, 9]])

W = {
    [
        a   b
        c   d
    ] within R_2x2 | 
    8a + 3b - c = 0
} of R_2x2

In [51]:
from sympy import symbols, Eq, solve, Matrix

# Define the equation
eq = Eq(8*a + 3*b - c, 0)

# Solve the equation for c
solution = solve(eq, c)[0]

# Define the matrices M1, M2, and M3
M1 = Matrix([[1, 0], [solution.subs({a:1, b:0}), 0]])
M2 = Matrix([[0, 1], [solution.subs({a:0, b:1}), 0]])
M3 = Matrix([[0, 0], [0, 1]])

print("M1:")
display(M1)

print("M2:")
display(M2)

print("M3:")
display(M3)

M1:


Matrix([
[1, 0],
[8, 0]])

M2:


Matrix([
[0, 1],
[3, 0]])

M3:


Matrix([
[0, 0],
[0, 1]])

# Ordered Basis

In [64]:
# v = np.array([[11], [3], [1]]) within R^3
# B = {np.array([[3], [1], [0]]), np.array([[0], [-1], [-]]), np.array([[2], [5], [1]])}


# Define the matrix A using the basis vectors and the vector v
B = np.array([[3, 0, 2], [1, -1, 5], [0, 0, 1]])
v = np.array([11, 3, 1])

# Use numpy's linalg.solve() function to solve for [x, y, z]
coords = np.linalg.solve(B, v)

coords

array([3., 5., 1.])

In [63]:
# Define the matrix A using the basis vectors and the vector v
B = np.array([[1, 0], [0, 1]])
v = np.array([7, 8])

# Use numpy's linalg.solve() function to solve for [x, y, z]
coords = np.linalg.solve(B, v)

coords

array([7., 8.])

In [71]:
# Define the basis vectors
u1 = np.array([9, -1])
u2 = np.array([-5, 4])

# Define the vector v
v = np.array([-18, 2])

# Create a matrix from the basis vectors
B = np.column_stack((u1, u2))

# Use the np.linalg.inv function to compute the inverse of the matrix B
# Then use the np.dot function to multiply this inverse with the vector v
coordinates = np.dot(np.linalg.inv(B), v)

coordinates

# Answer:
# np.array([[-2], [0]])

array([-2.0000000e+00,  6.9388939e-17])

In [73]:
# Define the basis vectors
u1 = np.array([-3, -8, -5])
u2 = np.array([4, -1, 8])
u3 = np.array([-7, 1, 0])

# Define the vector v
v = np.array([5, 9, -19])

# Create a matrix from the basis vectors
B = np.column_stack((u1, u2, u3))

# Use the np.linalg.inv function to compute the inverse of the matrix B
# Then use the np.dot function to multiply this inverse with the vector v
coordinates = np.dot(np.linalg.inv(B), v)

coordinates

array([-1., -3., -2.])

In [75]:
# Define the matrix A
A = np.array([
    [2, 9],
    [8, 7]
])

# Flatten the matrix to get the coordinates with respect to the standard basis
coordinates = A.flatten()

coordinates

array([2, 9, 8, 7])

In [76]:
# Define the matrix A
A = np.array([
    [-20, -32],
    [-27, -12]
])

# Flatten the matrix to get the coordinates with respect to the standard basis
coordinates = A.flatten()

coordinates

array([-20, -32, -27, -12])

In [78]:
# Define the basis matrices
A1 = np.array([[3, 9], [8, -1]])
A2 = np.array([[-3, -4], [-9, -6]])
A3 = np.array([[-3, -5], [7, -8]])
A4 = np.array([[2, -9], [8, -7]])

# Define the matrix A
A = np.array([[-20, -32], [-27, -12]])

# Create a matrix from the basis matrices
B = np.column_stack((A1.flatten(), A2.flatten(), A3.flatten(), A4.flatten()))

# Use the np.linalg.inv function to compute the inverse of the matrix B
# Then use the np.dot function to multiply this inverse with the flattened matrix A
coordinates = np.dot(np.linalg.inv(B), A.flatten())

coordinates

array([-3.,  1.,  2., -1.])

In [81]:
# Define the polynomial p
p = 7 + 6*x

# Create a Poly object from the polynomial
poly = Poly(p)

# Get the coefficients of the polynomial
coefficients = poly.all_coeffs()

coefficients

[6, 7]

In [82]:
# Define the polynomial p
p = 10 - 2*x

# Create a Poly object from the polynomial
poly = Poly(p)

# Get the coefficients of the polynomial
coefficients = poly.all_coeffs()

coefficients

[-2, 10]

In [83]:
# Given the ordered basis B = {p1 = 4 - x, p2 = -4 - 7x}, 
# find the coordinates of p = 4 - 17x with respect to B

# Define the coefficients of the basis polynomials
p1 = np.array([4, -1])
p2 = np.array([-4, -7])

# Define the coefficients of the polynomial p
p = np.array([4, -17])

# Create a matrix from the coefficients of the basis polynomials
B = np.column_stack((p1, p2))

# Use the np.linalg.inv function to compute the inverse of the matrix B
# Then use the np.dot function to multiply this inverse with the coefficients of p
coordinates = np.dot(np.linalg.inv(B), p)

coordinates

array([3., 2.])

In [85]:
# Define the vectors in the bases B and C
B = np.array([[1, -4], [2, 5]])
C = np.array([[-2, -8], [7, 4]])

# Solve the system of equations represented by the augmented matrix for each column of C
P = np.linalg.solve(B, C)

P

array([[ 1.38461538, -1.84615385],
       [ 0.84615385,  1.53846154]])

In [93]:
# Define the matrix A and the vector v
A = np.array([[-12, 2], [36, -6]])
v = np.array([-2, -12])

# Perform the matrix multiplication Av
Av = np.dot(A, v)
display(Av)

# Check if v is in the null space of A
is_in_null_space = np.all(Av == 0)
print("Is v in null(A)?", is_in_null_space)


array([0, 0])

Is v in null(A)? True


# Rank and Nullity

In [94]:
# Define the matrix A
A = np.array([[8, -16], [-6, 12]])

# Find the rank of A
rank = np.linalg.matrix_rank(A)
print("Rank of A:", rank)

# Find the nullity of A
nullity = A.shape[1] - rank
print("Nullity of A:", nullity)

Rank of A: 1
Nullity of A: 1


In [95]:
# Define the matrix A
A = np.array([[1, -4, 0, -2, -3], [0, 0, 1, -3, 4], [0, 0, 0, 0, 0]])

# Find the rank of A
rank = np.linalg.matrix_rank(A)
print("Rank of A:", rank)

# Find the nullity of A
nullity = A.shape[1] - rank
print("Nullity of A:", nullity)

Rank of A: 2
Nullity of A: 3
