In [57]:
import sympy as smp
from sympy import *
import numpy as np
from numpy import *
import scipy as sp
from scipy.integrate import solve_ivp
from scipy.interpolate import interp1d
from scipy.integrate import odeint
from fractions import Fraction
import matplotlib.pyplot as plt
import scienceplots
plt.style.use(['science', 'notebook', 'grid'])

x, y, t, n, a, b, C, c, r, u, s, A = smp.symbols('x y t n a b C c r u s A')
f, g, m = smp.symbols('f g m', cls=smp.Function)

# 1

In [2]:
# Define the coefficient matrix and constant vector
A = np.array([[2, -2], [0, 1]])
b = np.array([-20, 5])

# Solve the system of equations
np.linalg.solve(A, b)

array([-5.,  5.])

In [3]:
# Define the coefficient matrix and constant vector
A = np.array([[1, 1], [-3, -2]])
b = np.array([-3, 10])

# Solve the system of equations
np.linalg.solve(A, b)

array([-4.,  1.])

In [4]:
# Solve for x_1 and x_2

# x_1 - 3x_2 = 5
# x_1 - 2x_2 = 2

# Define the coefficient matrix and constant vector
A = np.array([[1, -3], [1, -2]])
b = np.array([5, 2])

np.linalg.solve(A, b)

array([-4., -3.])

In [5]:
# Solve for x_1, x_2, x_3

# x_1 + 2x_2 - 6x_3 = 25
# 2x_1 + 5x_2 - 15x_3 = 64
# -3x_1 - 6x_2 + 19x_3 = -79

A = np.array([[1, 2, -6], [2, 5, -15], [-3, -6, 19]])
b = np.array([25, 64, -79])

np.linalg.solve(A, b)

array([-3.,  2., -4.])

In [6]:
# Solve for x_1, x_2, x_3

# x_1 + 3x_2 + 3x_3 = 14
# x_1 + 4x_2 + 4x_3 = 18
# 2x_1 + 6x_2 + 7x_3 = 29

A = np.array([[1, 3, 3], [1, 4, 4], [2, 6, 7]])
b = np.array([14, 18, 29])

np.linalg.solve(A, b)

array([2., 3., 1.])

# 2

In [7]:
A = np.array([[2, 4], [-2, 1], [5, 9]])
B = np.array([[5, -8], [4, 6], [7, -5]])

np.subtract(A, B)
#np.add(A, B)

array([[-3, 12],
       [-6, -5],
       [-2, 14]])

In [8]:
A = np.array([[0, 8, 9], [-2, -4, 1]])
B = np.array([[5, -7, -1], [-3, 2, -9]])

np.add(A, B)

array([[ 5,  1,  8],
       [-5, -2, -8]])

In [9]:
A = np.array([[-2, 1], [4, 0]])
B = np.array([[2, -3], [0, -8]])

np.add(A, B)

array([[ 0, -2],
       [ 4, -8]])

In [10]:
A = np.array([[3, -5], [7, -3], [-2, 1]])
B = np.array([[4, -1], [6, 2], [1, 1]])
C = np.array([[2, 4], [-1, 5], [0, 2]])

Ans1 = np.subtract(A, B)
Ans2 = np.add(Ans1, C)

Ans2

array([[ 1,  0],
       [ 0,  0],
       [-3,  2]])

In [11]:
# DNE

A = np.array([[-1, -2, 1], [0, 2, 4], [0, 0, -2]])
B = np.array([[5, -1], [1, 0]])
C = np.array([[4, 2, 1], [5, 0, 2], [-1, 1, 5]])

Ans1 = np.multiply(B, 2)
Ans2 = np.add(Ans1, C)

Ans2

ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

In [12]:
A = np.array([[-1, -2, 1], [0, 2, 4], [0, 0, -2]])
B = np.array([[5, -1], [1, 0]])
C = np.array([[4, 2, 1], [5, 0, 2], [-1, 1, 5]])

Ans1 = np.add(C, A)
Ans2 = np.multiply(Ans1, 2)
Ans2

array([[ 6,  0,  4],
       [10,  4, 12],
       [-2,  2,  6]])

In [13]:
A = np.array([[-1, -2, 1], [0, 2, 4], [0, 0, -2]])
B = np.array([[5, -1], [1, 0]])
C = np.array([[4, 2, 1], [5, 0, 2], [-1, 1, 5]])

Ans1 = np.multiply(C, 3)
Ans2 = np.subtract(A, Ans1)

Ans2

array([[-13,  -8,  -2],
       [-15,   2,  -2],
       [  3,  -3, -17]])

In [14]:
A = np.array([[1, -1, 2], [3, 4, 0]])
B = np.array([[0, 0, 0], [0, 0, 0]])

np.add(A,B)

array([[ 1, -1,  2],
       [ 3,  4,  0]])

In [15]:
A = np.array([[1, -1, 1], [-1, 1, -1], [1, -1, 1]])
B = np.array([[1, -1, 1], [-1, 1, -1], [1, -1, 1]])

A1 = np.multiply(A, 2)
A2 = np.multiply(B, 3)

np.add(A1, A2)

array([[ 5, -5,  5],
       [-5,  5, -5],
       [ 5, -5,  5]])

In [16]:
A = np.array([[4, 8], [-12, -4]])

np.multiply(A, 2)

array([[  8,  16],
       [-24,  -8]])

In [17]:
A = np.array([[-7, -9], [-3, -2]])
B = np.array([[4, -8], [7, 1]])

np.add(A, B)

array([[ -3, -17],
       [  4,  -1]])

In [18]:
A = np.array([[-9, 4], [-1, -4]])
B = np.array([[2, -2], [8, 6]])

np.subtract(A, B)

array([[-11,   6],
       [ -9, -10]])

In [19]:
A = np.array([[-1, 7], [6, -9]])
B = np.array([[4, 1], [-3, 5]])

Ans1 = np.multiply(A, -4)
Ans2 = np.add(Ans1, B)

Ans2

array([[  8, -27],
       [-27,  41]])

In [20]:
A = np.array([[-6, 8], [2, 4]])
B = np.array([[-7, -8], [0, -1]])

Ans = np.add(A, B)
np.multiply(Ans, 4)

array([[-52,   0],
       [  8,  12]])

In [21]:
A = np.array([[3, -1, 5]])
B = np.array([[6], [0], [4]])

np.multiply(A, B)

array([[18, -6, 30],
       [ 0,  0,  0],
       [12, -4, 20]])

In [22]:
A = np.array([[-1, 0], [0, 2], [-3, 4]])
B = np.array([[1, 0], [3, -2]])

# Non-element-wise matrix multiplication
np.dot(A, B)

array([[-1,  0],
       [ 6, -4],
       [ 9, -8]])

In [23]:
A = np.array([[3, -1], [0, 4]])
B = np.array([[0, 1, -2], [1, 0, 3], [-1, 5, 2]])
C = np.array([[2, -2], [1, 0]])
D = np.array([[1, 0], [0, 3], [-2, 5]])

#np.dot(A, C)
#np.dot(D, C)
np.dot(B, D)

array([[ 4, -7],
       [-5, 15],
       [-5, 25]])

In [24]:
A = np.array([[0, 1], [-2, -1]])
B = np.array([[-1, 1], [-2, 0]])

np.dot(A, B)

array([[-2,  0],
       [ 4, -2]])

In [25]:
A = np.array([[-1, -3, 1], [2, -2, 0]])
B = np.array([[1, -1], [0, -3], [-2, 2]])

np.dot(A, B)

array([[-3, 12],
       [ 2,  4]])

In [26]:
A = np.array([[-1, 0, 4], [2, -3, 1], [3, -2, -4]])
B = np.array([[3, -2, 0], [1, -4, 2], [-1, -3, 4]])

np.dot(A, B)

array([[ -7, -10,  16],
       [  2,   5,  -2],
       [ 11,  14, -20]])

In [27]:
A = np.array([[7, 0, 0], [0, 5, 0], [0, 0, 6]])
B = np.array([[8, 0, 0], [0, 4, 0], [0, 0, 1]])

np.dot(A, B)

array([[56,  0,  0],
       [ 0, 20,  0],
       [ 0,  0,  6]])

In [28]:
A = np.array([[1, 0], [0, -2]])

np.linalg.matrix_power(A, 3)

array([[ 1,  0],
       [ 0, -8]])

In [29]:
A = np.array([[1, 0], [0, 1]])
B = np.array([[-2, 2], [-7, -5]])

np.dot(B, A)

array([[-2,  2],
       [-7, -5]])

In [30]:
I = np.array([[1, 0], [0, 1]])
A = np.array([[-7, 5], [7, -6]])
B = np.array([[-7, 8], [-2, 9]])

Ans = np.add(A, B)
np.dot(I, Ans)

array([[-14,  13],
       [  5,   3]])

In [31]:
A = np.array([[5, 2], [-3, -7]])
B = np.array([[1, 2], [6, -2]])
C = np.array([[-2, -5], [3, 5]])

Ans1 = np.multiply(A, B)
Ans2 = np.multiply(A, C)
Ans3 = np.add(Ans1, Ans2)
np.divide(Ans3, A)

array([[-1., -3.],
       [ 9.,  3.]])

In [32]:
A = np.array([[6, 2], [3, -5]])
B = np.array([[2, 7], [-1, 1]])
C = np.array([[9, 7], [2, 0]])

Ans1 = np.multiply(B, A)
Ans2 = np.multiply(C, A)
Ans3 = np.add(Ans1, Ans2)
np.divide(Ans3, A)

array([[11., 14.],
       [ 1.,  1.]])

In [33]:
A = np.array([[9, -3], [2, -9]])
B = np.array([[2, 1], [-3, -6]])

Ans1 = np.multiply(A, B)
Ans2 = np.multiply(Ans1, 3)
np.divide(Ans2, A)

array([[  6.,   3.],
       [ -9., -18.]])

In [34]:
A = np.array([[4, -1], [-7, 2]])

np.linalg.matrix_power(A, -1)

array([[2., 1.],
       [7., 4.]])

In [35]:
A = np.array([[3, 2], [0, 1]])

np.linalg.matrix_power(A, -1)

array([[ 0.33333333, -0.66666667],
       [ 0.        ,  1.        ]])

In [36]:
A = np.array([[(1/3), 0], [0, (4/3)]])

np.linalg.matrix_power(A, -1)

array([[3.  , 0.  ],
       [0.  , 0.75]])

In [37]:
A = np.array([[1, -1, -1], [0, 3, 5], [1, 1, 2]])

np.linalg.matrix_power(A, -1)

array([[-1., -1.,  2.],
       [-5., -3.,  5.],
       [ 3.,  2., -3.]])

In [38]:
A = np.array([[5, -4], [-6, 5]])

np.linalg.matrix_power(A, -1)

array([[5., 4.],
       [6., 5.]])

In [39]:
# DNE

A = np.array([[(2/5), (-3/5)]])

np.linalg.matrix_power(A, -1)

LinAlgError: Last 2 dimensions of the array must be square

In [40]:
A = np.array([[-2, 3], [-5, 9]])

np.linalg.matrix_power(A, -1)

array([[-3.        ,  1.        ],
       [-1.66666667,  0.66666667]])

In [41]:
A = np.array([[1, 0], [2, 1]])

np.linalg.matrix_power(A, -1)

array([[ 1.,  0.],
       [-2.,  1.]])

In [42]:
A = np.array([[(-1/4), 0, 0], [0, (-1/8), 0], [0, 0, (1/2)]])

np.linalg.matrix_power(A, -1)

array([[-4., -0., -0.],
       [-0., -8., -0.],
       [ 0.,  0.,  2.]])

In [43]:
A = np.array([[1, 0, -3], [3, 1, -6], [0, 1, 4]])

np.linalg.matrix_power(A, -1)

array([[ 10.,  -3.,   3.],
       [-12.,   4.,  -3.],
       [  3.,  -1.,   1.]])

In [44]:
A = np.array([[-4, -7], [-1, -2]])

np.linalg.matrix_power(A, -1)

array([[-2.,  7.],
       [ 1., -4.]])

In [45]:
# Elementary Row Operation = Use np.dot

A = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
B = np.array([[-9, -7, 6], [0, -5, -4], [7, -8, 2]])

np.dot(A, B)

array([[-9, -7,  6],
       [ 7, -8,  2],
       [ 0, -5, -4]])

In [46]:
# Elementary Row Operation = Use np.dot

A = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])
B = np.array([[1, 5, 4], [3, 7, -1], [-7, -2, 9]])

np.dot(A, B)

array([[ 1,  5,  4],
       [-7, -2,  9],
       [ 3,  7, -1]])

In [47]:
# Elementary Row Operation = Use np.dot

A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, -2]])
B = np.array([[0, 6, 2], [-7, 9, -1], [-2, 7, 4]])

np.dot(A, B)

array([[  0,   6,   2],
       [ -7,   9,  -1],
       [  4, -14,  -8]])

In [48]:
# Elementary Row Operation = Use np.dot

A = np.array([[1, 0, 0], [0, 1, 1], [0, 0, 1]])
B = np.array([[8, -7, -3], [4, 9, 6], [-8, -1, -6]])

np.dot(A, B)

array([[ 8, -7, -3],
       [-4,  8,  0],
       [-8, -1, -6]])

In [49]:
# Elementary Row Operation = Use np.dot

A = np.array([[1, 0, 0], [0, 1, 0], [0, 4, 1]])
B = np.array([[-2, 9, 1], [-1, -8, 5], [3, -3, 6]])

np.dot(A, B)

array([[ -2,   9,   1],
       [ -1,  -8,   5],
       [ -1, -35,  26]])

# Linear System of Equations

In [4]:
# 3x_1 + x_2 = 2
# x_1 - 4x_2 = 5

# A^-1 = (1/13) ([[4, 1], [1, -3]])

# Define the symbols
x1, x2 = symbols('x1 x2')

# Define the equations
eq1 = Eq(3*x1 + x2, 2)
eq2 = Eq(x1 - 4*x2, 5)

# Use sympy.linsolve to solve the system of equations
solution = linsolve([eq1, eq2], (x1, x2))

solution

{(1, -1)}

In [5]:
# -2x_1 + x_2 = -7
# 3x_1 + 2x_2 = 0

# A^-1 = (1/7) ([[-1, 1], [3, 2]])

# Define the symbols
x1, x2 = symbols('x1 x2')

# Define the equations
eq1 = Eq(-2*x1 + x2, -7)
eq2 = Eq(3*x1 + 2*x2, 0)

# Use sympy.linsolve to solve the system of equations
solution = linsolve([eq1, eq2], (x1, x2))

solution

{(2, -3)}

In [6]:
# 5x_1 + 6x_2 = -3
# x_1 + 2x_2 + 3x_3 = 0
# x_2 + 4x_3 = 1

# A^-1 = ([[5, -24, 18], [-4, 20, -15], [1, -5, 4]])

# Define the symbols
x1, x2, x3 = symbols('x1 x2 x3')

# Define the equations
eq1 = Eq(5*x1 + 6*x2, -3)
eq2 = Eq(x1 + 2*x2 + 3*x3, 0)
eq3 = Eq(x2 + 4*x3, 1)

# Use sympy.linsolve to solve the system of equations
solution = linsolve([eq1, eq2, eq3], (x1, x2, x3))

solution

{(3, -3, 1)}

In [7]:
# x_1 - x_2 + x_3 = 3
# 2x_1 + x_2 + 3x_3 = 2
# -x_1 + 2x_2 + x_3 = -1

# A^-1 = (1/5)([[-5, 3, -4], [-5, 2, -1], [5, -1, 3]])

# Define the symbols
x1, x2, x3 = symbols('x1 x2 x3')

# Define the equations
eq1 = Eq(x1 - x2 + x3, 3)
eq2 = Eq(2*x1 + x2 + 3*x3, 2)
eq3 = Eq(-x1 + 2*x2 + x3, -1)

# Use sympy.linsolve to solve the system of equations
solution = linsolve([eq1, eq2, eq3], (x1, x2, x3))

solution

{(-1, -2, 2)}

In [9]:
# -x_1 + x_2 = 1
# -3x_1 + 2x_2 = -1

# A^-1 = ([[2, -1], [3, -1]])

# Define the symbols
x1, x2 = symbols('x1 x2')

# Define the equations
eq1 = Eq(-x1 + x2, 1)
eq2 = Eq(-3*x1 + 2*x2, -1)

# Use sympy.linsolve to solve the system of equations
solution = linsolve([eq1, eq2], (x1, x2))

solution

{(3, 4)}

In [10]:
# 2x_1 - 3x_2 = -3
# -5x_1 + 8x_2 = 2

# Define the symbols
x1, x2 = symbols('x1 x2')

# Define the equations
eq1 = Eq(2*x1 - 3*x2, -3)
eq2 = Eq(-5*x1 + 8*x2, 2)

# Use sympy.linsolve to solve the system of equations
solution = linsolve([eq1, eq2], (x1, x2))

solution

{(-18, -11)}

# LU Decomposition

Given that A is transformed into U by the elementary row operations below, find (E_1)^-1 and (E_2)^-1:

A = ([[8, -2, 3], [-24, 13, -4], [-16, 4, -4]])

2R1 + R3 -> R3

([[8, -2, 3], [-24, 13, -4], [0, 0, 2]])

3R1 + R2 -> R2

U = ([[8, -2, 3], [0, 7, 5], [0, 0, 2]])

In [68]:
# Define the matrix A and U
A = np.array([[8, -2, 3], [-24, 13, -4], [-16, 4, -4]])
U = np.array([[8, -2, 3], [0, 7, 5], [0, 0, 2]])

# Start with identity matrices for E1 and E2
E1 = np.eye(3)
E2 = np.eye(3)

# Perform the operations on E1 and E2
E1[2] = 2*E1[0] + E1[2] # 2R1 + R3 -> R3
E2[1] = 3*E2[0] + E2[1] # 3R1 + R2 -> R2

# Print the elementary matrices E1 and E2
print("E1 = ")
print(E1)
print("\nE2 = ")
print(E2)

E1 = 
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 1.]]

E2 = 
[[1. 0. 0.]
 [3. 1. 0.]
 [0. 0. 1.]]


In [66]:
np.linalg.matrix_power(E1, -1)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-2., -0.,  1.]])

In [67]:
np.linalg.matrix_power(E2, -1)

array([[ 1.,  0.,  0.],
       [-3.,  1., -0.],
       [ 0.,  0.,  1.]])

Given that A is transformed into U by the elementary row operations below, find (E_1)^-1 and (E_2)^-1:

A = ([[-7, -4, 6], [21, 19, -16], [14, 8, -7]])

2R1 + R3 -> R3

([[-7, -4, 6], [21, 19, -16], [0, 0, 5]])

3R1 + R2 -> R2

U = ([[-7, -4, 6], [0, 7, 2], [0, 0, 5]])

In [69]:
# Define the matrix A and U
A = np.array([[-7, -4, 6], [21, 19, -16], [14, 8, -7]])
U = np.array([[-7, -4, 6], [0, 7, 2], [0, 0, 5]])

# Start with identity matrices for E1 and E2
E1 = np.eye(3)
E2 = np.eye(3)

# Perform the operations on E1 and E2
E1[2] = 2*E1[0] + E1[2] # 2R1 + R3 -> R3
E2[1] = 3*E2[0] + E2[1] # 3R1 + R2 -> R2

# Print the elementary matrices E1 and E2
print("E1 = ")
print(E1)
print("\nE2 = ")
print(E2)

E1 = 
[[1. 0. 0.]
 [0. 1. 0.]
 [2. 0. 1.]]

E2 = 
[[1. 0. 0.]
 [3. 1. 0.]
 [0. 0. 1.]]


In [70]:
np.linalg.matrix_power(E1, -1)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-2., -0.,  1.]])

In [71]:
np.linalg.matrix_power(E2, -1)

array([[ 1.,  0.,  0.],
       [-3.,  1., -0.],
       [ 0.,  0.,  1.]])

Given that A is transformed into U by the elementary row operations below, find L

A = ([[-5, -6, -8], [15, 11, 26], [-10, -12, -9]])

-2R1 + R3 -> R3

([[-5, -6, -8], [15, 11, 26], [0, 0, 7]])

3R1 + R2 -> R2

U = ([[-5, -6, -8], [0, -7, 2], [0, 0, 7]])

L = (E1)^-1 * (E2)^-1

In [76]:
# Define the matrix A and U
A = np.array([[-5, -6, -8], [15, 11, 26], [-10, -12, -9]])
U = np.array([[-5, -6, -8], [0, -7, 2], [0, 0, 7]])

# Start with identity matrices for E1 and E2
E1 = np.eye(3)
E2 = np.eye(3)

# Perform the operations on E1 and E2
E1[2] = -2*E1[0] + E1[2] # -2R1 + R3 -> R3
E2[1] = 3*E2[0] + E2[1] # 3R1 + R2 -> R2

# Print the elementary matrices E1 and E2
print("E1 = ")
print(E1)
print("\nE2 = ")
print(E2)

E1 = 
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-2.  0.  1.]]

E2 = 
[[1. 0. 0.]
 [3. 1. 0.]
 [0. 0. 1.]]


In [80]:
A = np.linalg.matrix_power(E1, -1)
B = np.linalg.matrix_power(E2, -1)

np.dot(A, B)

array([[ 1.,  0.,  0.],
       [-3.,  1.,  0.],
       [ 2.,  0.,  1.]])

Given that A is transformed into U by the elementary row operations below, find L

A = ([[3, 2, 8], [9, -2, 25], [-9, -6, -33]])

3R1 + R3 -> R3

([[3, 2, 8], [9, -2, 25], [0, 0, -9]])

-3R1 + R2 -> R2

U = ([[3, 2, 8], [0, -8, 1], [0, 0, -9]])

L = (E1)^-1 * (E2)^-1

In [83]:
# Define the matrix A and U
A = np.array([[3, 2, 8], [9, -2, 25], [-9, -6, -33]])
U = np.array([[3, 2, 8], [0, -8, 1], [0, 0, -9]])

# Start with identity matrices for E1 and E2
E1 = np.eye(3)
E2 = np.eye(3)

# Perform the operations on E1 and E2
E1[2] = 3*E1[0] + E1[2] # 3R1 + R3 -> R3
E2[1] = -3*E2[0] + E2[1] # -3R1 + R2 -> R2

# Print the elementary matrices E1 and E2
print("E1 = ")
print(E1)
print("\nE2 = ")
print(E2)

E1 = 
[[1. 0. 0.]
 [0. 1. 0.]
 [3. 0. 1.]]

E2 = 
[[ 1.  0.  0.]
 [-3.  1.  0.]
 [ 0.  0.  1.]]


In [84]:
A = np.linalg.matrix_power(E1, -1)
B = np.linalg.matrix_power(E2, -1)

np.dot(A, B)

array([[ 1.,  0.,  0.],
       [ 3.,  1.,  0.],
       [-3.,  0.,  1.]])

Given the matrices below and that A = LU, solve Ax = b

A = ([[1, 1, -4], [-3, -2, 10], [3, -3, 1]])

b = ([[-4], [13], [-16]])

L = ([[1, 0, 0], [-3, 1, 0], [3, -6, 1]])

U = ([[1, 1, -4], [0, 1, -2], [0, 0, 1]])

In [85]:
# Define the matrices L, U, and b
L = np.array([[1, 0, 0], [-3, 1, 0], [3, -6, 1]])
U = np.array([[1, 1, -4], [0, 1, -2], [0, 0, 1]])
b = np.array([[-4], [13], [-16]])

# Solve the system Ly = b for y
y = np.linalg.solve(L, b)

# Solve the system Ux = y for x
x = np.linalg.solve(U, y)

# Print the solution x
print("x = ")
x

x = 


array([[-1.],
       [ 5.],
       [ 2.]])

Given the matrices below and that A = LU, complete L^-1 * U^-1 and A^-1

A = ([[1, -5, 5], [4, -19, 23], [2, -9, 14]])

L = ([[1, 0, 0], [4, 1, 0], [2, 1, 1]])

U = ([[1, -5, 5], [0, 1, 3], [0, 0, 1]])

In [86]:
A = np.array([[1, -5, 5], [4, -19, 23], [2, -9, 14]])
L = np.array([[1, 0, 0], [4, 1, 0], [2, 1, 1]])
U = np.array([[1, -5, 5], [0, 1, 3], [0, 0, 1]])

print("A^-1 = ")
print(np.linalg.matrix_power(A, -1))

print("L^-1 = ")
print(np.linalg.matrix_power(L, -1))

print("U^-1 = ")
print(np.linalg.matrix_power(U, -1))

A^-1 = 
[[-59.  25. -20.]
 [-10.   4.  -3.]
 [  2.  -1.   1.]]
L^-1 = 
[[ 1.  0.  0.]
 [-4.  1.  0.]
 [ 2. -1.  1.]]
U^-1 = 
[[  1.   5. -20.]
 [  0.   1.  -3.]
 [  0.   0.   1.]]
