In [72]:
import sympy as smp
from sympy import *
import numpy as np
from numpy import *
import scipy as sp
from scipy.integrate import solve_ivp
from scipy.interpolate import interp1d
from scipy.integrate import odeint
from fractions import Fraction
import matplotlib.pyplot as plt
import scienceplots
plt.style.use(['science', 'notebook', 'grid'])

x, y, t, n, a, b, C, c, r, u, s, A, d = smp.symbols('x y t n a b C c r u s A d')
f, g, m = smp.symbols('f g m', cls=smp.Function)

# Evaluating transformations

T: R^2 -> R^2

T(x) = [
    (x1)(x2)
    
    (x1)^2 + (x2)^2
]

T([1

   1]) = ?

In [2]:
def T(x):
    return np.array([x[0]*x[1], x[0]**2 + x[1]**2])

x = np.array([1, 1])
result = T(x)

result

array([1, 2])

T: R^3 -> R^2

T(x) = [
    2x1 + x2 + x3

    x1 - x2 - x3
]

T([

    1

    1

    1
]) = ?

In [3]:
def T(x):
    return np.array([2*(x[0]) + x[1] + x[2], x[0] - x[1] - x[2]])

x = np.array([1, 1, 1])
result = T(x)

result

array([ 4, -1])

In [4]:
def T(x):
    return np.array([x[0] + x[1], 0, x[1] - 3])

x = np.array([1, 1])
result = T(x)

result

array([ 2,  0, -2])

In [5]:
def T(x):
    return np.array([5*(x[0]) + x[1], 5*(x[1]), x[0] - 4*(x[1])])

x = np.array([-1, 0])
result = T(x)

result

array([-5,  0, -1])

In [6]:
def T(x):
    return np.array([5*(x[0]) + x[1], 3*(x[1]), x[0] - 4*(x[1])])

x = np.array([5, 1])
result = T(x)

result

array([26,  3,  1])

In [8]:
def T(x):
    return np.array([3*(x[0]) - x[1] - x[2], x[0] + 4*(x[2])])

x = np.array([-3, 1, 2])
result = T(x)

result

array([-12,   5])

Let T be an operator on R^2 that projects a vector onto a line L

This makes an angle of theta = 60 degrees with respect to the horizontal axis x1. 

What is the unit vector v in the direction of L?

In [9]:
# Convert the angle to radians
theta = np.deg2rad(60)

# Calculate the components of the unit vector
v1 = np.cos(theta)
v2 = np.sin(theta)

# Create the unit vector
v = np.array([v1, v2])

v

array([0.5      , 0.8660254])

In [19]:
# T(e1)

def T(u, v):
    return (np.dot(u, v) / np.dot(v, v)) * v

e1 = np.array([1, 0])
v = np.array([0.5, 0.866])

T1 = T(e1, v)

T1

array([0.250011  , 0.43301905])

In [18]:
# T(e2)

def T(u, v):
    return (np.dot(u, v) / np.dot(v, v)) * v

e2 = np.array([0, 1])
v = np.array([0.5, 0.866])

T2 = T(e2, v)

T2

array([0.43301905, 0.749989  ])

In [33]:
# Use the standart matrix to find the projection of v = np.array([5, -3])
# on to the line which makes a 60 degree angle with the horizontal axis

def T(u, v):
    return (np.dot(v, u)) * u

v = np.array([5, -3])
u = np.array([0.5, 0.866])

result = T(u, v)

result

array([-0.049   , -0.084868])

In [35]:
def T(a1, a2, a3):
    return [2*a1 - a2, -3*a2 + 5*a3]

result = T(5, 2, 6)

result

[8, 24]

In [36]:
def T(x1, x2):
    return [[-4*x1, 5*x2], [3*x2, 2*x1]]

result = T(1, 3)

result

[[-4, 15], [9, 2]]

In [40]:
# Let T: (rho)1 -> (rho)2 be the linear transformation defined by:
# T(ax^2 + bx + c) = (d/dx)(ax^2 + bx + c)
# T(2x^2 + 3x + 2)

# Define the polynomial
polynomial = 2*x**2 + 3*x + 2

# Compute the derivative
derivative = smp.diff(polynomial, x)

derivative

4*x + 3

# Standard Matrices are reversed

In [47]:
# Let T: (Rho)1 -> R^2 be a linear transformation defined by 
# T((a1)x + a2) = [-2a1, 4a2]
# Let B = {1, x} be a basis for (Rho)1 and B' = {[[1, 0], [0, 1]]} be a basis for R^2

def T(a1, a2):
    return [-2*a1, 4*a2]

# Apply the transformation to the basis vectors
result1 = T(1, 0)  # Coefficients for x
result2 = T(0, 1)  # Coefficients for 1

# Combine the results into a matrix
standard_matrix = [result1, result2]

standard_matrix
# The answer is reversed

[[-2, 0], [0, 4]]

In [49]:
def T(a1, a2):
    return [-5*a1, 4*a2]

# Apply the transformation to the basis vectors
result1 = T(1, 0)  # Coefficients for x
result2 = T(0, 1)  # Coefficients for 1

# Combine the results into a matrix
standard_matrix = [result1, result2]

standard_matrix
# The answer is reversed

[[-5, 0], [0, 4]]

In [51]:
def T(x1, x2):
    return [9*x1 + 6*x2, 2*x1 + 8*x2]

# Apply the transformation to the basis vectors
result1 = T(1, 0)  # Coefficients for x
result2 = T(0, 1)  # Coefficients for 1

# Combine the results into a matrix
standard_matrix = [result1, result2]

standard_matrix
# The answer is reversed

[[9, 2], [6, 8]]

In [52]:
def T(a1, a2):
    return [-5*a1, 2*a2]

# Apply the transformation to the basis vectors
result1 = T(1, 0)  # Coefficients for x
result2 = T(0, 1)  # Coefficients for 1

# Combine the results into a matrix
standard_matrix = [result1, result2]

standard_matrix

[[-5, 0], [0, 2]]

In [54]:
def T(x1, x2):
    return [9*x1 + 6*x2, 4*x1 + 3*x2]

# Apply the transformation to the basis vectors
result1 = T(1, 0)  # Vector [1, 0]
result2 = T(0, 1)  # Vector [0, 1]

# Combine the results into a matrix
standard_matrix = [result1, result2]

standard_matrix
# Answer = [[9, 6], [4, 3]]

[[9, 4], [6, 3]]

In [56]:
def T(a, b):
    return [b, -4*a - b]

# Apply the transformation to the basis vectors
result1 = T(1, 0)  # Vector [1, 0]
result2 = T(0, 1)  # Vector [0, 1]

# Combine the results into a matrix
standard_matrix = [result1, result2]

standard_matrix
# Answer = [[0, 1], [-4, -1]]

[[0, -4], [1, -1]]

In [58]:
def T(matrix):
    a, b, c, d = matrix.flatten()
    return [3*(a+b), 6*(c+d)]

# Define the basis matrices
basis_matrices = [
    np.array([[1, 0], [0, 0]]),
    np.array([[0, 1], [0, 0]]),
    np.array([[0, 0], [1, 0]]),
    np.array([[0, 0], [0, 1]])
]

# Apply the transformation to the basis matrices
results = [T(matrix) for matrix in basis_matrices]

# Combine the results into a matrix
standard_matrix = np.column_stack(results)

standard_matrix

array([[3, 3, 0, 0],
       [0, 0, 6, 6]])

T((a1)x + a2) = [[5a1, 4a2]]

Using the basis {-2x - 7, -3x}

In [59]:
def T(a1, a2):
    return [5*a1, 4*a2]

# Apply the transformation to the coefficients of the basis polynomials
result1 = T(-2, -7)  # Coefficients for -2x - 7
result2 = T(-3, 0)  # Coefficients for -3x

# Combine the results into a list
basis_R2 = [result1, result2]

basis_R2

[[-10, -28], [-15, 0]]

In [60]:
def T(a1, a2, a3):
    return f"{7*a2}x^2 + {2*a1 + a3}x + {8*a1}"

# Apply the transformation to the vectors in the basis
result1 = T(1, 0, 0)  # Vector [1, 0, 0]
result2 = T(0, 1, 0)  # Vector [0, 1, 0]
result3 = T(0, 0, 1)  # Vector [0, 0, 1]

# Combine the results into a list
basis_P2 = [result1, result2, result3]

basis_P2

['0x^2 + 2x + 8', '7x^2 + 0x + 0', '0x^2 + 1x + 0']

# Compositions of Linear Transformations

In [61]:
def T1(x):
    return np.array([4*x[0], 3*x[0] + 2*x[1]])

def T2(x):
    return np.array([-5*x[0], -2*x[1]])

x = np.array([-1, -3])

# Apply T2 to x
x = T2(x)

# Apply T1 to the result
x = T1(x)

x

array([20, 27])

In [62]:
# Part I
# T1 ∘ T2

def T1(x):
    return np.array([-3*x[0], -5*x[0] + 4*x[1]])

def T2(x):
    return np.array([-4*x[0], 2*x[1]])

x = np.array([-1, 1])

# Apply T2 to x
x = T2(x)

# Apply T1 to the result
x = T1(x)

x

array([-12, -12])

In [63]:
# Part II
# T2 ∘ T1

def T1(x):
    return np.array([-3*x[0], -5*x[0] + 4*x[1]])

def T2(x):
    return np.array([-4*x[0], 2*x[1]])

x = np.array([-1, 1])

# Apply T1 to x
x = T1(x)

# Apply T2 to the result
x = T2(x)

x

array([-12,  18])

In [69]:
def T1(a, b, c):
    return np.array([a + b, b - c])

def T2(x):
    return np.array([[-3*x[0], 3*x[0]], [-7*x[1], -5*x[1]]])

# Coefficients of the quadratic polynomial -4x^2 + 3x + 2
a, b, c = -4, 3, 2

# Apply T1 to the coefficients
x = T1(a, b, c)

# Apply T2 to the result
x = T2(x)

x

array([[ 3, -3],
       [-7, -5]])

In [73]:
def T(x):
    return np.array([x[0], x[0] + x[1]])

u = np.array([3, 4])

# Apply T to u
Tu = T(u)

print("T(u) =", Tu)

# Basis vectors
v1 = np.array([1, 2])
v2 = np.array([0, 1])

# Matrix with basis vectors as columns
C = np.column_stack((v1, v2))

# Solve for the coordinates of Tu in the basis C
coords = np.linalg.solve(C, Tu)

print("[T(u)]_C =", coords)

T(u) = [3 7]
[T(u)]_C = [3. 1.]


In [76]:
def T(x):
    return np.array([2*x[0] - x[1], -3*x[2]])

# Basis vectors for B
u1 = np.array([7, 1, -5])
u2 = np.array([4, -4, -1])
u3 = np.array([-6, -2, -3])

# Apply T to each vector in B
Tu1 = T(u1)
Tu2 = T(u2)
Tu3 = T(u3)

# Basis vectors for C
v1 = np.array([3, 7])
v2 = np.array([-6, 0])

# Matrix with basis vectors for C as columns
C = np.column_stack((v1, v2))

# Augmented matrix for the system of equations to express T(ui) in terms of C
augmented_matrix = np.column_stack((C, Tu1, Tu2, Tu3))

print("Augmented matrix:")
print(augmented_matrix)

Augmented matrix:
[[  3  -6  13  12 -10]
 [  7   0  15   3   9]]


In [80]:
def T(x):
    return np.array([x[0], x[0] - x[1]])

# Basis vectors for B
u1 = np.array([0, -3])
u2 = np.array([5, 2])

# Apply T to each vector in B
Tu1 = T(u1)
Tu2 = T(u2)

# Basis vectors for C
v1 = np.array([1, -3])
v2 = np.array([0, 1])

# Matrix with basis vectors for C as columns
C = np.column_stack((v1, v2))

# Convert to sympy matrices for solving
C_sympy = Matrix(C)
Tu1_sympy = Matrix(Tu1)
Tu2_sympy = Matrix(Tu2)

# Solve for the coordinates of Tu1 and Tu2 in the basis C
c1, c2 = symbols('c1 c2')
sol_Tu1 = linsolve((C_sympy, Tu1_sympy), c1, c2)
sol_Tu2 = linsolve((C_sympy, Tu2_sympy), c1, c2)

# The matrix representation of T with respect to the bases B and C
T_C_B = np.column_stack((list(sol_Tu1)[0], list(sol_Tu2)[0]))

print("[T]^C_B:")
print(T_C_B)

[T]^C_B:
[[0 5]
 [3 18]]


In [88]:
# Define the vectors u1 and u2
u1 = np.array([5, 2])
u2 = np.array([2, 1])

# Create the matrix B using u1 and u2 as columns
B = np.column_stack((u1, u2))

# Compute the inverse of B to get the transition matrix P_B
P_B = np.linalg.inv(B)

print(P_B)

[[ 1. -2.]
 [-2.  5.]]
